# Generated by Django 5.2.5 on 2025-08-15 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0002_alter_petition_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petition',
            name='until',
            field=models.DateTimeField(null=True),
        ),
    ]
