# Generated by Django 5.2.5 on 2025-08-16 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0003_alter_petition_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petition',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestor.item'),
        ),
    ]
