# Generated by Django 5.2.5 on 2025-08-16 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0004_alter_petition_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='conditions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='type',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
