# Generated by Django 5.2.5 on 2025-08-16 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0005_type_conditions_alter_type_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='date_reserved',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
