# Generated by Django 5.2.5 on 2025-08-19 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0008_alter_item_code_alter_item_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='item',
            name='is_blocked',
        ),
        migrations.RemoveField(
            model_name='petition',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='petition',
            name='is_pending',
        ),
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('blocked', 'Blocked'), ('in_use', 'In Use')], default='available', max_length=40),
        ),
        migrations.AddField(
            model_name='petition',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('PENDING', 'Pending'), ('ACTIVE', 'Active')], default='AVAILABLE', max_length=40),
        ),
    ]
