# Generated by Django 5.2.5 on 2025-08-19 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0009_remove_item_is_available_remove_item_is_blocked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petition',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gestor.item'),
        ),
        migrations.AlterField(
            model_name='petition',
            name='status',
            field=models.CharField(choices=[('DECLINED', 'Declined'), ('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('COLLECTED', 'Collected')], default='PENDING', max_length=40),
        ),
    ]
