# Generated by Django 5.2.5 on 2025-08-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0010_alter_petition_item_alter_petition_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petition',
            name='status',
            field=models.CharField(choices=[('DECLINED', 'Declined'), ('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('COLLECTED', 'Collected')], default='PENDING', max_length=40),
        ),
    ]
