# Generated by Django 5.2.5 on 2025-08-23 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0011_alter_petition_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='is_blocked',
        ),
        migrations.AddField(
            model_name='type',
            name='status',
            field=models.CharField(choices=[('BLOCKED', 'Blocked'), ('AVAILABLE', 'Available')], default='AVAILABLE', max_length=40),
        ),
    ]
