# Generated by Django 5.2.5 on 2025-08-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0012_remove_type_is_blocked_type_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
