# Generated by Django 5.2.5 on 2025-08-12 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('is_bool', models.BooleanField(default=False)),
            ],
        ),
    ]
