# Generated by Django 5.2.5 on 2025-08-12 13:43

from django.db import migrations


class Migration(migrations.Migration):

    def seed_settings(apps, schema_editor):
        Configuration = apps.get_model('configuracion', 'Configuration')

        defaults =[
            {
                'node': 'app_name',
                'value': 'PrestaDA',
                'description': 'El nombre que aparece en la cabecera',
                'is_bool': False,
            },
            {
                'node': 'org',
                'value': 'DA-ETSIAE',
                'description': 'Nombre de la organización, aparece en la pestaña y es parte del menú',
                'is_bool': False,
            },
            {
                'node': 'org_link',
                'value': 'https://aeroespacial.da.upm.es/',
                'description': 'Enlace a la organización',
                'is_bool': False,
            },
            {
                'node': 'maintenance_kind',
                'value': 'False',
                'description': 'Activa el modo mantenimiento simpático',
                'is_bool': True,
            },
            {
                'node': 'maintenance_title',
                'value': 'En mantenimiento',
                'description': 'Título en modo mantenimiento',
                'is_bool': False,
            },
            {
                'node': 'maintenance_description',
                'value': 'Modo Mantenimiento Activado',
                'description': 'Descripción en modo mantenimiento',
                'is_bool': False,
            },
            {
                'node': 'maintenance_ugly',
                'value': 'False',
                'description': 'Activda el modo mantenimiento feo',
                'is_bool': True,
            },
            {
                'node': 'maintenance_ugly_code',
                'value': '418',
                'description': 'Código HTTP a arrojar en mantenimiento feo',
                'is_bool': False,
            },
            {
                'node': 'login_text',
                'value': '',
                'description': 'Texto que aparece al entrar',
                'is_bool': False,
            },
            {
                'node': 'contact_email',
                'value': 'tic.da.aeroespacial@upm.es',
                'description': 'Email de contacto',
                'is_bool': False,
            },
            {
                'node': 'agreement_title',
                'value': 'Acuerdo DA-ETSIAE',
                'description': 'Título del contrato pdf',
                'is_bool': False,
            },
            {
                'node': 'agreement_header',
                'value': 'Acuerdo DA-ETSIAE',
                'description': 'Cabecera del contrato pdf',
                'is_bool': False,
            },
        ]

        for config in defaults:
            Configuration.objects.update_or_create(
                node=config['node'],
                defaults={
                    'value': config['value'],
                    'description': config['description'],
                    'is_bool': config['is_bool'],
                }

            )

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_settings),
    ]