# Generated by Django 5.2.5 on 2025-08-13 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0002_auto_20250812_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='node',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
