# Generated by Django 5.2.5 on 2025-08-18 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='description',
            field=models.CharField(choices=[('AUTH', 'Auth'), ('LOGOUT', 'Logout'), ('UPDATE', 'Update'), ('CREATE', 'Create'), ('DELETE', 'Delete')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='ip_address',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user_agent',
            field=models.TextField(null=True),
        ),
    ]
