# Generated by Django 5.2.5 on 2025-08-18 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_auditlog_description_alter_auditlog_ip_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='audit_type',
            field=models.CharField(choices=[('AUTH', 'Auth'), ('LOGOUT', 'Logout'), ('UPDATE', 'Update'), ('CREATE', 'Create'), ('DELETE', 'Delete')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
