# Generated by Django 5.2.5 on 2025-08-18 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_auditlog_audit_type_alter_auditlog_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='audit_type',
            field=models.CharField(choices=[('AUTH', 'Auth'), ('LOGOUT', 'Logout'), ('UPDATE', 'Update'), ('CREATE', 'Create'), ('DELETE', 'Delete'), ('URGENT', 'Urgent')], max_length=50, null=True),
        ),
    ]
