# Generated by Django 5.2.5 on 2025-08-19 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_alter_auditlog_audit_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='audit_type',
            field=models.CharField(choices=[('Auth', 'Auth'), ('Create', 'Create'), ('Update', 'Update'), ('Delete', 'Delete'), ('Fail', 'Fail'), ('Urgent', 'Urgent')], max_length=50, null=True),
        ),
    ]
