# Generated by Django 5.2.5 on 2025-08-15 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mensajes', '0002_globalalert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermessage',
            name='is_active',
        ),
    ]
