# Generated by Django 5.2.5 on 2025-08-17 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajes', '0003_remove_usermessage_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalmessage',
            name='has_title',
            field=models.BooleanField(default=True),
        ),
    ]
