# Generated by Django 5.2.5 on 2025-08-17 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mensajes', '0004_alter_globalmessage_has_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GlobalAlert',
        ),
    ]
