# Generated by Django 5.2.5 on 2025-08-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajes', '0005_delete_globalalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessage',
            name='is_from_staff',
            field=models.BooleanField(default=False),
        ),
    ]
