# Generated by Django 5.2.5 on 2025-08-19 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajes', '0006_usermessage_is_from_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalmessage',
            name='color',
            field=models.CharField(choices=[('green', 'primary'), ('blue', 'link'), ('red', 'danger'), ('yellow', 'warning')], default='green', max_length=20),
        ),
    ]
