# Generated by Django 5.2.5 on 2025-08-19 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajes', '0007_alter_globalmessage_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalmessage',
            name='has_title',
        ),
        migrations.AlterField(
            model_name='globalmessage',
            name='color',
            field=models.CharField(choices=[('primary', 'Primary'), ('link', 'Blue'), ('danger', 'Danger'), ('warning', 'Yellow')], default='primary', max_length=20),
        ),
    ]
