# Generated by Django 5.2.5 on 2025-08-19 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajes', '0008_remove_globalmessage_has_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalmessage',
            name='color',
            field=models.CharField(choices=[('text', 'Black'), ('link', 'Blue'), ('primary', 'Greenish Blue'), ('info', 'Light Blue'), ('success', 'Green'), ('warning', 'Yellow'), ('danger', 'Red')], default='success', max_length=20),
        ),
    ]
