name: Build/Push Docker image
on:
  push:
    branches:
      - main

jobs:
    build:
      permissions:
        packages: write
        contents: read
      name: push to dockerhub
      runs-on: ubuntu-24.04
      steps:
        - uses: actions/checkout@v5
        
        - name: Build
          run: docker build . --file Dockerfile 
          
        - name: Login
          run: docker login -u ${{vars.DOCKERHUB_USERNAME}} -p ${{secrets.DOCKERHUB_PASSWORD}}
          
        - name: Push
          id: push-docker-image
          run: docker push ${{vars.DOCKERHUB_USERNAME}}/prestamos:latest
